














name: Create Issue
description: All issues except ones relating to specific CLI tools
title: ""
labels: [NEED_TO_LABEL]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues) to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Issue Summary
    description: Summarise your issue
    placeholder: e.g. the autocomplete popup sometimes doesn't appear after changing tabs
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Output of `fig diagnostic`
    description: Run `fig diagnostic` and paste the output below. If you can't, tell us any information you think is relevant (OS, m1 etc)
    render: bash
  validations:
    required: false
- type: dropdown
  attributes:
    label: Specific Terminal?
    options:
      - native macOS terminal
      - VSCode
      - iTerm2
      - Hyper
    multiple: true
- type: dropdown
  attributes:
    label: Specific Shell?
    options:
      - bash
      - zsh
      - fish
      - other
    multiple: true
- type: dropdown
  attributes:
    label: Specific Integration?
    options:
      - ssh
      - docker
      - tmux
    multiple: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
