name: Create Issue
description: All issues except ones relating to specific CLI tools
title: "ISSUE TITLE"
labels: [NEED_TO_LABEL]
body:
- type: checkboxes
  attributes:
    label: Have you searched for a duplicate issue?
    options:
    - label: I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues) and there are no duplicates
      required: true
- type: textarea
  attributes:
    label: Issue Details
    description: What happens? What do you expect? How do we reproduce?
    value: |
    ### Summary 
    e.g. Autocomplete is occasionally nonresponsive
    
    ### Steps to Reproduce
    1. ..
    2. ..
    
    ### Expected Results
    e.g. Autocomplete suggestion box should always pop up.
    
    
    ### Actual Results
    e.g. Occasionally, the suggestion box disappears and reappears after entering a few commands.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: Run `fig diagnostic` and paste the output below. If you can't, tell us any information you think is relevant (OS, m1 etc)
    render: bash
  validations:
    required: true
- type: dropdown
  attributes:
    label: More Detail
    description: Is your issue specifically related to one of the following terminals, shells, or integrations? ? 
    options:
      - terminal: native macOS terminal
      - terminal: VSCode
      - terminal: iTerm2
      - terminak: Hyper
      - shell: bash
      - shell: zsh
      - shell: fish
      - integration: ssh
      - integration: docker
      - integration: tmux
    multiple: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
