name: Main Issue Template
description: All issues except ones relating to specific CLI tools
labels: [NEED_TO_LABEL]
body:
- type: checkboxes
  attributes:
    label: Sanity checks
    options:
    - label: "I have searched [github.com/withfig/fig/issues](https://github.com/withfig/fig/issues?q=) and there are no duplicates of my issue"
      required: true
- type: textarea
  attributes:
    label: Issue Details
    description: What happens? What do you expect? How do we reproduce?
    # Because we are using hashtags at the start of a line, we must put the value in quotes. We cannot use YAML's multiline syntax with the pipe symbol
    value: "### Summary\ne.g. Autocomplete is occasionally non-responsive (add an image or screen recording if applicable)\n\n### Steps to Reproduce\n1. ..\n2. ..\n\n### Expected Results\ne.g. Autocomplete suggestion box should always pop up."
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: Run `fig diagnostic` and paste the output below. If you can't, tell us any information you think is relevant (OS, m1 etc)
    render: bash
  validations:
    required: true
